name: Build & Deploy to QuantCDN

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - run: pip install -r requirements.txt
      - run: mkdocs build --config-file mkdocs.yml

      - name: Deploy updates to QuantCDN
        uses: quantcdn/deploy-action@v2.0.0
        with:
          customer: "${{ secrets.QUANT_CUSTOMER_ID }}"
          project: "${{ secrets.QUANT_PROJECT_ID }}"
          token: "${{ secrets.QUANT_TOKEN }}"
          endpoint: "${{ secrets.QUANT_ENDPOINT || 'https://api.quantcdn.io' }}"
          dir: site
          chunk-size: 20
          skip-purge: true
          revision-log: .quant-revision

      - name: Purge the QuantCDN cache
        uses: quantcdn/purge-action@v2.0.0
        with:
          customer: "${{ secrets.QUANT_CUSTOMER_ID }}"
          project: "${{ secrets.QUANT_PROJECT_ID }}"
          token: "${{ secrets.QUANT_TOKEN }}"
          endpoint: "${{ secrets.QUANT_ENDPOINT || 'https://api.quantcdn.io' }}"
          url_pattern: "/*"